### ISSUE TITLE
Beavers hit and death animations

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/cyberpunk-beavers#31]

**Comment by stasiakmatt** [comment]
Part 4, First eta scheduled by Joe around 16-19 of July, due to short vacations they have and load of work. 
12.07.2024: we are on schedule, no info concerning any delays at this point.

Beavers - list of graphics and animations: https://docs.google.com/document/d/12lbSbFVbigYbHiQor32PkNndQGCGzlt79tMd9Fo72-A/edit?usp=sharing
